"""Authenticated loopback task-control dashboard shell."""

from __future__ import annotations


DASHBOARD_HTML = r'''<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Agent Control</title>
  <style>
    :root {
      color-scheme: light;
      --ink:#17211b; --muted:#66736c; --paper:#f4f1e9; --panel:#fffdf8;
      --line:#d9d8ce; --green:#1f6b4f; --green-soft:#dceee5; --lime:#dfff73;
      --amber:#a76318; --amber-soft:#fff0cf; --red:#a63f3a; --red-soft:#fbe3df;
      --blue:#2f5e87; --shadow:0 22px 70px rgba(32,48,39,.10);
    }
    *{box-sizing:border-box} body{margin:0;min-height:100vh;background:var(--paper);color:var(--ink);font:15px/1.5 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    button,input,textarea,select{font:inherit} button{cursor:pointer}
    .shell{display:grid;grid-template-columns:230px minmax(0,1fr);min-height:100vh}
    aside{position:sticky;top:0;height:100vh;padding:26px 20px;border-right:1px solid var(--line);background:#ebe9e0;display:flex;flex-direction:column}
    .brand{display:flex;align-items:center;gap:11px;font-weight:800;font-size:18px;letter-spacing:-.03em}.mark{display:grid;place-items:center;width:34px;height:34px;border-radius:11px;background:var(--ink);color:var(--lime);font-weight:900}
    nav{display:grid;gap:6px;margin-top:34px}.nav{border:0;background:transparent;text-align:left;padding:10px 12px;border-radius:10px;color:var(--muted)}.nav.active{background:var(--panel);color:var(--ink);font-weight:700;box-shadow:0 4px 18px rgba(32,48,39,.06)}
    .aside-foot{margin-top:auto;color:var(--muted);font-size:12px}.health{display:flex;align-items:center;gap:8px;margin-bottom:8px}.dot{width:9px;height:9px;border-radius:50%;background:#96a09a}.dot.live{background:#39a56f;box-shadow:0 0 0 5px rgba(57,165,111,.12)}
    main{min-width:0;padding:30px clamp(20px,4vw,54px) 60px}.top{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;margin-bottom:26px}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase;color:var(--green)}h1{margin:5px 0 0;font-size:clamp(30px,4vw,48px);line-height:1;letter-spacing:-.055em}h2{font-size:18px;margin:0;letter-spacing:-.025em}.sub{color:var(--muted);margin:9px 0 0}.top-actions{display:flex;align-items:center;gap:8px}
    .button{border:1px solid var(--line);background:var(--panel);color:var(--ink);border-radius:11px;padding:10px 14px;font-weight:700;transition:.16s ease}.button:hover{transform:translateY(-1px);border-color:#aeb7b1}.button.primary{background:var(--ink);color:white;border-color:var(--ink)}.button.primary:hover{background:var(--green)}.button.danger{color:var(--red)}.button.small{padding:7px 10px;font-size:12px}.button:disabled{opacity:.5;cursor:wait;transform:none}
    .layout{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);gap:18px}.stack{display:grid;gap:18px;align-content:start}.panel{background:var(--panel);border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);padding:22px;min-width:0}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.badge{display:inline-flex;align-items:center;max-width:100%;border-radius:99px;padding:4px 9px;background:#efeee8;color:var(--muted);font-size:11px;font-weight:800;white-space:normal;overflow-wrap:anywhere}
    label{display:grid;gap:7px;color:var(--muted);font-size:12px;font-weight:700}.field,textarea,select{width:100%;border:1px solid var(--line);border-radius:11px;background:white;color:var(--ink);padding:11px 12px;outline:none}.field:focus,textarea:focus,select:focus{border-color:var(--green);box-shadow:0 0 0 3px rgba(31,107,79,.1)}textarea{min-height:168px;resize:vertical;line-height:1.5}.form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.field-note{font-size:11px;line-height:1.35;color:var(--muted);font-weight:500}.form-actions{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-top:15px}.hint{font-size:12px;color:var(--muted)}
    .check-row{display:flex;grid-column:1/-1;align-items:flex-start;gap:10px;margin-top:2px;padding:11px 12px;border:1px solid var(--line);border-radius:11px;background:#faf8f2}.check-row input{width:auto;margin-top:3px}.check-row span{display:grid;gap:2px;color:var(--ink)}.check-row small{color:var(--muted);font-weight:500}.batch-area{min-height:210px;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.batch-form{display:grid;gap:12px;margin-top:14px}.batch-help{margin:0;padding:11px 12px;border-radius:11px;background:#faf8f2;color:var(--muted);font-size:12px}.batch-rows{display:grid;gap:10px}.batch-task{display:grid;gap:11px;padding:14px;border:1px solid var(--line);border-radius:14px;background:#faf8f2}.batch-task-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.batch-task-head strong{font-size:13px}.batch-goal{min-height:92px}.batch-check{display:flex;align-items:flex-start;gap:9px;color:var(--ink);font-size:12px;font-weight:700}.batch-check input{width:auto;margin-top:3px}.batch-check span{display:grid;gap:2px}.batch-check small{color:var(--muted);font-weight:500}.batch-options{display:grid;grid-template-columns:minmax(180px,260px) 1fr;gap:12px;align-items:end}.batch-actions{display:flex;justify-content:space-between;align-items:end;gap:9px;flex-wrap:wrap}.batch-actions>div{display:flex;gap:8px;flex-wrap:wrap}.advanced-batch{margin-top:4px!important;padding-top:12px!important}
    .stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{padding:15px;border:1px solid var(--line);border-radius:14px;background:#faf8f2}.stat-value{font-size:27px;font-weight:850;letter-spacing:-.04em}.stat-label{font-size:11px;color:var(--muted);margin-top:3px}
    .attention-list,.task-list{display:grid;gap:10px}.empty{padding:22px;border:1px dashed var(--line);border-radius:13px;text-align:center;color:var(--muted)}.attention{border:1px solid #e8c782;background:var(--amber-soft);border-radius:14px;padding:15px}.attention-title{font-weight:800}.attention p{margin:6px 0;color:#755026}.attention textarea{min-height:82px;margin:10px 0;background:#fffdf8}.answer-control{width:100%;margin-top:10px}.answer-description{flex-basis:100%;min-height:18px;margin-top:5px!important}.row-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.row-actions .answer-control{flex-basis:100%}
    .task{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;padding:15px 0;border-bottom:1px solid var(--line)}.task:last-child{border-bottom:0}.task-title{font-weight:800;overflow-wrap:anywhere}.task-goal{color:var(--muted);font-size:13px;margin-top:4px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.task-meta{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px;font-size:11px;color:var(--muted)}.task-side{text-align:right;min-width:118px}.status-pill{display:inline-flex;border-radius:99px;padding:4px 9px;font-size:11px;font-weight:850;background:#efeee8}.s-completed{background:var(--green-soft);color:var(--green)}.s-running,.s-claimed,.s-leased,.s-resuming,.s-repairing{background:#e0ebf5;color:var(--blue)}.s-awaiting_approval,.s-blocked{background:var(--amber-soft);color:var(--amber)}.s-failed,.s-dead_letter{background:var(--red-soft);color:var(--red)}.s-cancelled{color:var(--muted)}
    .filters{display:flex;gap:7px;flex-wrap:wrap}.filter{border:1px solid var(--line);background:transparent;border-radius:99px;padding:6px 10px;font-size:11px;color:var(--muted)}.filter.active{background:var(--ink);border-color:var(--ink);color:white}.filter-selects{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:8px;margin-bottom:14px;align-items:end}.filter-selects select{padding:8px 9px;font-size:12px}.filter-field{gap:4px}.filter-caption{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}
    .guide{display:grid;gap:12px}.guide-step{display:grid;grid-template-columns:27px 1fr;gap:10px;align-items:start}.guide-number{display:grid;place-items:center;width:27px;height:27px;border-radius:9px;background:var(--green-soft);color:var(--green);font-weight:850;font-size:12px}.guide-step strong{display:block;font-size:13px}.guide-step span:last-child{display:block;color:var(--muted);font-size:12px;margin-top:2px}
    details.settings{margin-top:18px;border-top:1px solid var(--line);padding-top:14px;color:var(--muted)}details summary{cursor:pointer;font-weight:700}.settings-grid{display:grid;gap:10px;margin-top:12px}
    .toast{position:fixed;right:24px;bottom:24px;z-index:20;max-width:min(430px,calc(100vw - 32px));padding:13px 16px;border-radius:12px;background:var(--ink);color:white;box-shadow:var(--shadow);opacity:0;transform:translateY(12px);pointer-events:none;transition:.2s}.toast.show{opacity:1;transform:none}.toast.error{background:var(--red)}
    @media(max-width:980px){.shell{grid-template-columns:1fr}aside{position:static;height:auto;padding:14px 20px;display:flex;flex-direction:row;align-items:center;gap:20px}.aside-foot{margin-left:auto;margin-top:0}nav{display:none}.layout{grid-template-columns:1fr}.top{margin-top:8px}}
    @media(max-width:620px){main{padding:22px 14px 44px}.top{display:grid;min-width:0}.top-actions{justify-content:space-between;min-width:0}.panel{padding:17px;border-radius:15px}.form-grid,.filter-selects,.batch-options{grid-template-columns:minmax(0,1fr)}.form-grid>*,.filter-selects>*,.batch-options>*{min-width:0}.form-actions{align-items:stretch;flex-direction:column}.form-actions .button{width:100%}.batch-actions{display:grid}.batch-actions>div{display:grid}.batch-actions .button{width:100%}.task{grid-template-columns:minmax(0,1fr)}.task-side{text-align:left}.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.aside-foot .health span:last-child{display:none}}
  </style>
</head>
<body>
<div class="shell">
  <aside>
    <div class="brand"><span class="mark">A</span><span>Agent Control</span></div>
    <nav><button class="nav active">Задачи</button><button class="nav" id="jumpAttention">Нужно внимание</button><button class="nav" id="jumpHistory">История</button></nav>
    <div class="aside-foot"><div class="health"><span class="dot" id="healthDot"></span><span id="healthText">Подключение…</span></div><div id="lastRefresh">Локальная система</div></div>
  </aside>
  <main>
    <header class="top">
      <div><div class="eyebrow">Рабочий центр</div><h1>Задание — в работу.</h1><p class="sub">Опишите результат — система подготовит ветку, выполнит работу и покажет, когда понадобится ваше решение.</p></div>
      <div class="top-actions"><button class="button" id="refresh">Обновить</button><button class="button primary" id="focusTask">Новая задача</button></div>
    </header>
    <div class="layout">
      <div class="stack">
        <section class="panel" id="newTaskPanel">
          <div class="panel-head"><div><h2>Запустить одну задачу</h2><div class="hint">Если задач несколько, откройте простой конструктор ниже.</div></div><span class="badge">⌘ Enter</span></div>
          <form id="taskForm">
            <label>Что нужно сделать<textarea id="goal" maxlength="20000" placeholder="Опишите результат, ограничения и критерии готовности…" required></textarea></label>
            <div class="form-grid">
              <label>Режим выполнения<select id="executionMode"><option value="auto">Авто — рекомендуется</option><option value="adaptive">Адаптивно — экспериментально</option><option value="fast">Быстро — до 15 минут</option><option value="full">Тщательно — до 60 минут</option><option value="goal">Долгая цель — до 4 часов</option></select><span class="field-note" id="executionModeNote">Адаптивный режим строит минимальный безопасный план, но останется экспериментальным до прохождения сравнительной оценки.</span></label>
              <label>Где выполнять задачу<select id="workspaceMode"><option value="new_branch">Новая безопасная ветка — обычно</option><option value="current_branch">В текущей ветке — для опытных</option><option value="worktree">В отдельной папке — параллельно</option></select><span class="field-note" id="workspaceModeNote">Подходит для обычной задачи: система создаст отдельную ветку в текущей папке проекта.</span></label>
              <label>Номер задачи — необязательно<input class="field" id="taskId" placeholder="Например, KC-432"></label>
              <label class="check-row"><input id="parallelTask" type="checkbox"><span>Параллельная задача<small>Включите, если в этом проекте уже выполняется другая задача. Система создаст отдельную рабочую папку и ветку.</small></span></label>
            </div>
            <div class="form-actions"><span class="hint" id="taskHint">Перед запуском система проверит проект и безопасно подготовит Git-ветку.</span><button class="button primary" id="submitTask" type="submit">Запустить задачу</button></div>
          </form>
          <details class="settings"><summary>Запустить несколько задач</summary><form id="batchForm" class="batch-form"><p class="batch-help">Добавьте задачи по одной. Они могут относиться к одному или разным проектам — технический формат и рабочие копии система подготовит сама.</p><div class="batch-rows" id="batchRows"></div><div class="batch-options"><label>Одновременно в одном проекте<select id="batchConcurrency"><option value="1">1 задача</option><option value="2" selected>До 2 задач — рекомендуется</option><option value="3">До 3 задач</option><option value="4">До 4 задач</option></select><span class="field-note">Ограничение защищает проект и тестовую базу от перегрузки.</span></label><span class="hint">Задачи с разрешённой параллельной работой получат отдельные рабочие копии и ветки.</span></div><div class="batch-actions"><button class="button" id="addBatchTask" type="button">+ Добавить ещё задачу</button><button class="button primary" id="submitBatch" type="submit">Запустить задачи</button></div></form><details class="settings advanced-batch"><summary>Расширенный режим: импорт YAML</summary><form id="yamlBatchForm" class="batch-form"><p class="batch-help">Этот формат нужен только для автоматизации и заранее подготовленных файлов. Для обычной работы используйте конструктор выше.</p><label>YAML-файл с задачами<textarea id="batchManifest" class="batch-area" spellcheck="false" placeholder="Вставьте содержимое YAML-файла или подставьте пример."></textarea></label><div class="batch-actions"><div><button class="button small" id="fillBatchExample" type="button">Подставить пример</button><button class="button small" id="clearBatch" type="button">Очистить</button></div><button class="button primary" id="submitYamlBatch" type="submit">Импортировать и запустить</button></div></form></details></details>
          <details class="settings"><summary>Настройки подключения</summary><div class="settings-grid"><label>Папка проекта<input class="field" id="repository" placeholder="/путь/к/проекту"></label><label>Токен локального сервера<input class="field" id="token" type="password" autocomplete="off"></label></div></details>
        </section>
        <section class="panel" id="attentionPanel"><div class="panel-head"><div><h2>Нужно ваше внимание</h2><div class="hint">Здесь появляются только вопросы, запросы на одобрение и задачи, которые нельзя продолжить автоматически.</div></div><span class="badge" id="attentionCount">0</span></div><div class="attention-list" id="attentionList"></div></section>
        <section class="panel" id="historyPanel"><div class="panel-head"><div><h2>Все задачи</h2><div class="hint">Выберите этап, затем при необходимости сузьте список.</div></div><div class="filters" id="filters"><button class="filter active" data-filter="all">Все</button><button class="filter" data-filter="queued" title="Queued">В очереди</button><button class="filter" data-filter="running" title="Running">В работе</button><button class="filter" data-filter="testing" title="Testing">Проверка</button><button class="filter" data-filter="needs_input" title="Needs input">Нужен ответ</button><button class="filter" data-filter="pr_ready" title="PR ready">PR готов</button><button class="filter" data-filter="failed" title="Failed">Ошибка</button></div></div><div class="filter-selects"><label class="filter-field"><span class="filter-caption">Репозиторий</span><select id="repositoryFilter"><option value="">Все репозитории</option></select></label><label class="filter-field"><span class="filter-caption">Ветка</span><select id="branchFilter"><option value="">Все ветки</option></select></label><label class="filter-field"><span class="filter-caption">Worker</span><select id="workerFilter"><option value="">Все workers</option></select></label><button class="button small" id="clearFilters" type="button">Сбросить</button></div><div class="task-list" id="taskList"></div></section>
      </div>
      <div class="stack">
        <section class="panel"><div class="panel-head"><h2>Сейчас</h2><span class="badge" id="serviceBadge">Проверяем</span></div><div class="stats" id="stats"></div></section>
        <section class="panel"><div class="panel-head"><h2>Worker</h2><span class="badge" id="workerBadge">—</span></div><div id="workerInfo" class="hint">Нет данных</div></section>
        <section class="panel"><div class="panel-head"><h2>Быстрый старт</h2></div><div class="guide"><div class="guide-step"><span class="guide-number">1</span><div><strong>Опишите результат</strong><span>Добавьте ограничения и критерии готовности — система сама выберет маршрут.</span></div></div><div class="guide-step"><span class="guide-number">2</span><div><strong>Выберите способ работы</strong><span>Для обычной задачи оставьте настройки как есть. Для одновременной работы включите «Параллельная задача».</span></div></div><div class="guide-step"><span class="guide-number">3</span><div><strong>Следите за этапом</strong><span>Очередь, реализация и проверки обновляются автоматически.</span></div></div><div class="guide-step"><span class="guide-number">4</span><div><strong>Отвечайте только при необходимости</strong><span>Вопрос или запрос на одобрение появится в блоке «Нужно ваше внимание». Слияние веток и развёртывание остаются за человеком.</span></div></div></div></section>
      </div>
    </div>
  </main>
</div>
<div class="toast" id="toast"></div>
<script>
const $=id=>document.getElementById(id), state={data:null,filter:'all',repository:'',branch:'',worker:'',busy:false,answers:{}};
const statusNames={queued:'В очереди',claimed:'Запускается',leased:'Запускается',running:'Выполняется',retry_wait:'Повтор',repairing:'Исправляется',resuming:'Продолжается',waiting_children:'Ждёт фоновые задачи',awaiting_approval:'Ждёт решения',blocked:'Остановлена',dead_letter:'Нужна проверка',failed:'Ошибка',completed:'Готово',cancelled:'Отменена'},lifecycleNames={queued:'В очереди',running:'В работе',testing:'Проверка',needs_input:'Нужен ответ',pr_ready:'PR готов',failed:'Ошибка'},executionModeNames={auto:'Авто',fast:'Быстро · 15 мин',full:'Тщательно · 60 мин',goal:'Долгая цель · 4 ч'};
const active=new Set(['queued','claimed','leased','running','retry_wait','repairing','resuming']);
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n}
function auth(){const token=$('token').value.trim();return token?{Authorization:`Bearer ${token}`}:{}}
async function api(path,{method='GET',body}={}){const headers={...auth()};if(body!==undefined)headers['Content-Type']='application/json';const r=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Ошибка ${r.status}`);return data}
let toastTimer;function toast(message,error=false){const n=$('toast');n.textContent=message;n.className=`toast show${error?' error':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.className='toast',4200)}
function metric(value,label){const n=el('div','stat');n.append(el('div','stat-value',value),el('div','stat-label',label));return n}
function runById(id){return (state.data?.runs?.items||[]).find(x=>x.run_id===id)}
function taskRepository(task){return task.payload?.repository||runById(task.run_id)?.repository||$('repository').value.trim()}
function renderStats(){const d=state.data,o=d.overview||{},host=$('stats');host.replaceChildren(metric(o.active_tasks||0,'выполняются'),metric(o.queue_depth||0,'в очереди'),metric(o.completed_last_24h||0,'готово за сутки'),metric(o.human_interventions||0,'ждут вас'));const alive=Boolean(d.service?.alive);$('healthDot').className=`dot${alive?' live':''}`;$('healthText').textContent=alive?'Система работает':'Worker не запущен';$('serviceBadge').textContent=alive?'Онлайн':'Нужна проверка';$('workerBadge').textContent=`${o.active_workers||0} активных`;$('workerInfo').textContent=alive?`Фоновый сервис работает · PID ${d.service?.pid||'—'}`:'Новая задача попробует запустить worker автоматически.';$('lastRefresh').textContent=`Обновлено ${new Date((d.generated_at||Date.now()/1000)*1000).toLocaleTimeString('ru-RU')}`}
function attentionAction(run,box){const action=run.attention?.action||'',isAnswer=['answer','answer_or_approve'].includes(action);if(isAnswer){const question=run.attention?.question||{},options=Array.isArray(question.options)?question.options:[],input=el('textarea','answer-control'),draftIdentity=run.attention?.fingerprint||run.attention?.summary||'',storedDraft=state.answers[run.run_id]||{},draft=storedDraft.identity===draftIdentity?storedDraft:{};let select=null,description=null;const saveDraft=()=>{state.answers[run.run_id]={identity:draftIdentity,choice:select?.value||'',custom:input.value}};if(options.length>=2){select=el('select','answer-control');options.forEach(item=>{const option=el('option','',`${item.label}${item.recommended?' — рекомендуется':''}`);option.value=item.value;option.dataset.description=item.description||'';select.append(option)});if(question.allow_custom){const custom=el('option','','Другой ответ…');custom.value='__custom__';select.append(custom)}if([...select.options].some(option=>option.value===draft.choice))select.value=draft.choice;description=el('p','hint answer-description','');input.placeholder='Введите свой ответ…';input.value=draft.custom||'';const syncChoice=()=>{const custom=select.value==='__custom__';input.hidden=!custom;description.textContent=custom?'':select.selectedOptions[0]?.dataset.description||'';saveDraft()};select.addEventListener('change',()=>{syncChoice();if(select.value==='__custom__')input.focus()});input.addEventListener('input',saveDraft);syncChoice();box.append(select,description,input)}else{input.placeholder='Введите ответ системе…';input.value=draft.custom||'';input.addEventListener('input',saveDraft);box.append(input)}const b=el('button','button primary small','Ответить и продолжить');b.addEventListener('click',()=>{const response=select&&select.value!=='__custom__'?select.value:input.value;runAction(run,'answer',{response})});box.append(b)}else{const approve=el('button','button primary small','Одобрить и продолжить');approve.addEventListener('click',()=>runAction(run,'approve',{reason:'Одобрено в локальном дашборде.'}));box.append(approve)}const abort=el('button','button danger small','Отменить');abort.addEventListener('click',()=>runAction(run,'abort'));box.append(abort)}
function renderAttention(){const runs=(state.data.runs?.items||[]).filter(r=>r.attention?.required||['awaiting_approval','blocked','dead_letter','failed'].includes(r.status));$('attentionCount').textContent=runs.length;const host=$('attentionList');host.replaceChildren();if(!runs.length){host.append(el('div','empty','Сейчас система не ждёт от вас решений.'));return}runs.sort((a,b)=>(b.updated_at||0)-(a.updated_at||0)).forEach(run=>{const card=el('article','attention');card.append(el('div','attention-title',run.task_id||run.run_id));const summary=run.attention?.summary||'Задача остановлена и требует решения.';card.append(el('p','',summary));(run.attention?.details||[]).slice(0,3).forEach(x=>card.append(el('p','hint',x)));const actions=el('div','row-actions');if(run.status==='blocked'||run.status==='dead_letter'||run.status==='failed'){const retry=el('button','button primary small','Исправлено — повторить');retry.addEventListener('click',()=>runAction(run,'retry'));actions.append(retry);const abort=el('button','button danger small','Отменить');abort.addEventListener('click',()=>runAction(run,'abort'));actions.append(abort)}else attentionAction(run,actions);card.append(actions);host.append(card)})}
function taskStage(task){return task.lifecycle_stage||'queued'}
function visibleTask(task){const run=runById(task.run_id),repo=task.payload?.repository||run?.repository||'',branch=task.payload?.task_branch||task.payload?.branch||run?.branch||'',worker=task.worker_id||'';return(state.filter==='all'||taskStage(task)===state.filter)&&(!state.repository||repo===state.repository)&&(!state.branch||branch===state.branch)&&(!state.worker||worker===state.worker)}
function syncSelect(id,values,selected,placeholder){const node=$(id),current=selected;node.replaceChildren(el('option','',placeholder));node.firstChild.value='';[...new Set(values.filter(Boolean))].sort().forEach(value=>{const option=el('option','',value);option.value=value;node.append(option)});node.value=[...node.options].some(option=>option.value===current)?current:''}
function conflictText(item){const first=runById(item.recommended_first_run_id)?.branch||(item.branches||[])[0]||'первую ветку',second=runById(item.recommended_rebase_run_id)?.branch||(item.branches||[])[1]||'вторую ветку';return `Вероятный конфликт (${item.overlap_count}): сначала завершите ${first}, затем обновите ${second} и повторите проверку`}
function renderTasks(){const sorted=[...(state.data.queue?.items||[])].sort((a,b)=>b.id-a.id),seen=new Set(),all=sorted.filter(task=>{const key=task.run_id||task.task_key||`queue:${task.id}`;if(seen.has(key))return false;seen.add(key);return true});syncSelect('repositoryFilter',all.map(task=>task.payload?.repository||runById(task.run_id)?.repository),state.repository,'Все репозитории');syncSelect('branchFilter',all.map(task=>task.payload?.task_branch||task.payload?.branch||runById(task.run_id)?.branch),state.branch,'Все ветки');syncSelect('workerFilter',all.map(task=>task.worker_id),state.worker,'Все workers');const tasks=all.filter(visibleTask),conflicts=state.data.conflicts?.items||[];const host=$('taskList');host.replaceChildren();if(!tasks.length){host.append(el('div','empty','По выбранным фильтрам задач нет.'));return}tasks.slice(0,50).forEach(task=>{const row=el('article','task'),main=el('div'),side=el('div','task-side');main.append(el('div','task-title',task.payload?.task_id||task.task_key));main.append(el('div','task-goal',task.payload?.goal||'Описание скрыто или недоступно.'));const meta=el('div','task-meta');const run=runById(task.run_id),executionMode=task.payload?.mode||run?.mode,repo=task.payload?.repository||run?.repository;if(executionMode)meta.append(el('span','badge',`Режим: ${executionModeNames[executionMode]||executionMode}`));[repo,task.payload?.branch||task.payload?.task_branch,run?.current_role,task.worker_id,task.run_id].filter(Boolean).forEach(x=>meta.append(el('span','badge',x)));const conflictKeys=new Set();conflicts.filter(item=>(item.run_ids||[]).includes(task.run_id)).forEach(item=>{const key=[...(item.run_ids||[])].sort().join('|');if(conflictKeys.has(key))return;conflictKeys.add(key);meta.append(el('span','badge',conflictText(item)))});main.append(meta);const stage=taskStage(task);side.append(el('span',`status-pill s-${task.status}`,`${lifecycleNames[stage]||stage} · ${statusNames[task.status]||task.status}`));if(task.run_id&&!['completed','cancelled'].includes(task.status)){const actions=el('div','row-actions');if(['blocked','dead_letter','failed'].includes(task.status)){const retry=el('button','button small','Повторить');retry.addEventListener('click',()=>runAction({...run,run_id:task.run_id,repository:taskRepository(task)},'retry'));actions.append(retry)}const abort=el('button','button danger small','Остановить');abort.addEventListener('click',()=>runAction({...run,run_id:task.run_id,repository:taskRepository(task)},'abort'));actions.append(abort);side.append(actions)}row.append(main,side);host.append(row)})}
function render(){if(!state.data)return;renderStats();renderAttention();renderTasks()}
async function load(silent=false,force=false){try{state.data=await api('/metrics');if(force||!$('attentionPanel').contains(document.activeElement))render()}catch(e){$('healthDot').className='dot';$('healthText').textContent='Нет подключения';if(!silent)toast(e.message,true)}}
async function runAction(run,action,extra={}){if(!run?.run_id)return toast('У задачи ещё нет run id.',true);if(action==='abort'&&!confirm('Остановить эту задачу? Ветка и файлы сохранятся.'))return;try{await api(`/ui/runs/${encodeURIComponent(run.run_id)}/${action}`,{method:'POST',body:{repository:run.repository||$('repository').value.trim(),...extra}});if(action==='answer')delete state.answers[run.run_id];toast(action==='abort'?'Задача остановлена.':'Команда принята. Выполнение продолжится автоматически.');await load(true,true)}catch(e){toast(e.message,true)}}
async function startTask(event){event.preventDefault();const goal=$('goal').value.trim();if(!goal)return toast('Сначала опишите задачу.',true);$('submitTask').disabled=true;$('submitTask').textContent='Запускаем…';try{const result=await api('/ui/tasks',{method:'POST',body:{repository:$('repository').value.trim(),goal,workspace_mode:$('workspaceMode').value,parallel:$('parallelTask').checked,execution_mode:$('executionMode').value,task_id:$('taskId').value.trim()}});$('goal').value='';$('taskId').value='';toast(`Задача ${result.task_id||''} принята и запущена.`);await load(true,true);$('historyPanel').scrollIntoView({behavior:'smooth'})}catch(e){toast(e.message,true)}finally{$('submitTask').disabled=false;$('submitTask').textContent='Запустить задачу'}}
let batchRowCounter=0;
function refreshBatchRows(){const rows=[...document.querySelectorAll('.batch-task')];rows.forEach((row,index)=>{row.querySelector('.batch-task-number').textContent=`Задача ${index+1}`;row.querySelector('.remove-batch-task').disabled=rows.length===1});$('submitBatch').textContent=rows.length===1?'Запустить 1 задачу':`Запустить ${rows.length} задачи`}
function addBatchRow(defaults={}){batchRowCounter+=1;const row=el('article','batch-task'),head=el('div','batch-task-head'),title=el('strong','batch-task-number','Задача'),remove=el('button','button danger small remove-batch-task','Убрать');remove.type='button';remove.addEventListener('click',()=>{row.remove();refreshBatchRows()});head.append(title,remove);const repoLabel=el('label','','Папка проекта'),repo=el('input','field batch-repository');repo.placeholder='/путь/к/проекту';repo.value=defaults.repository??$('repository').value.trim();repoLabel.append(repo);const goalLabel=el('label','','Что нужно сделать'),goal=el('textarea','batch-goal');goal.placeholder='Опишите результат и критерии готовности…';goal.maxLength=20000;goal.value=defaults.goal||'';goalLabel.append(goal);const check=el('label','batch-check'),parallel=el('input','batch-parallel');parallel.type='checkbox';parallel.checked=Boolean(defaults.parallel);const checkText=el('span','');checkText.append(document.createTextNode('Можно выполнять параллельно'),el('small','','Система создаст отдельную рабочую копию и ветку — разбираться в Git не нужно.'));check.append(parallel,checkText);row.append(head,repoLabel,goalLabel,check);$('batchRows').append(row);refreshBatchRows();return row}
function resetBatchBuilder(){const repository=$('repository').value.trim();$('batchRows').replaceChildren();addBatchRow({repository})}
async function startBatch(event){event.preventDefault();const rows=[...document.querySelectorAll('.batch-task')],repositories={},aliases=new Map(),tasks=[],maxParallel=Number($('batchConcurrency').value);for(const row of rows){const repository=row.querySelector('.batch-repository').value.trim(),goal=row.querySelector('.batch-goal').value.trim();if(!repository){row.querySelector('.batch-repository').focus();return toast('Укажите папку проекта для каждой задачи.',true)}if(!goal){row.querySelector('.batch-goal').focus();return toast('Опишите каждую задачу.',true)}if(!aliases.has(repository)){const alias=`project_${aliases.size+1}`;aliases.set(repository,alias);repositories[alias]={path:repository,max_parallel_tasks:maxParallel}}tasks.push({repo:aliases.get(repository),goal,parallel:row.querySelector('.batch-parallel').checked})}$('submitBatch').disabled=true;$('submitBatch').textContent='Запускаем задачи…';try{const result=await api('/ui/tasks/batch',{method:'POST',body:{version:1,repositories,tasks}});toast(`Принято задач: ${result.accepted?.length||0}; ошибок: ${result.errors?.length||0}.`,Boolean(result.errors?.length));if(!result.errors?.length)resetBatchBuilder();await load(true,true);$('historyPanel').scrollIntoView({behavior:'smooth'})}catch(e){toast(e.message,true)}finally{$('submitBatch').disabled=false;refreshBatchRows()}}
async function startYamlBatch(event){event.preventDefault();const manifest=$('batchManifest').value.trim();if(!manifest)return toast('Вставьте содержимое YAML-файла.',true);$('submitYamlBatch').disabled=true;$('submitYamlBatch').textContent='Импортируем…';try{const result=await api('/ui/tasks/batch',{method:'POST',body:{manifest}});toast(`Принято задач: ${result.accepted?.length||0}; ошибок: ${result.errors?.length||0}.`,Boolean(result.errors?.length));await load(true,true);$('historyPanel').scrollIntoView({behavior:'smooth'})}catch(e){toast(e.message,true)}finally{$('submitYamlBatch').disabled=false;$('submitYamlBatch').textContent='Импортировать и запустить'}}
function syncWorkspaceHelp(){const mode=$('workspaceMode').value,notes={new_branch:'Подходит для обычной задачи: система создаст отдельную ветку в текущей папке проекта.',current_branch:'Используйте только заранее подготовленную чистую ветку, которая уже открыта в проекте.',worktree:'Для одновременной работы система создаст отдельную рабочую папку и ветку.'};$('workspaceModeNote').textContent=notes[mode]||'';$('taskHint').textContent=mode==='worktree'?'Другие задачи в этом проекте смогут продолжать работу независимо.':'Перед запуском система проверит проект и безопасно подготовит Git-ветку.'}
function changeParallelMode(){const select=$('workspaceMode'),checked=$('parallelTask').checked;if(checked){select.dataset.previousValue=select.value;select.value='worktree';select.disabled=true}else{select.disabled=false;if(select.dataset.previousValue){select.value=select.dataset.previousValue;delete select.dataset.previousValue}}syncWorkspaceHelp()}
function batchTemplate(){const repository=$('repository').value.trim()||'/path/to/project';return `version: 1\nrepositories:\n  project:\n    path: ${JSON.stringify(repository)}\n    max_parallel_tasks: 2\ntasks:\n  - repo: project\n    goal: Первая задача\n  - repo: project\n    goal: Вторая параллельная задача\n    parallel: true\n`}
function clearTaskFilters(){state.filter='all';state.repository='';state.branch='';state.worker='';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));if(state.data)renderTasks()}
function bootstrap(){const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('token'))sessionStorage.setItem('harness-token',hash.get('token'));if(hash.get('repo'))sessionStorage.setItem('harness-repo',hash.get('repo'));if(location.hash)history.replaceState(null,'',location.pathname);$('token').value=sessionStorage.getItem('harness-token')||'';$('repository').value=sessionStorage.getItem('harness-repo')||'';$('token').addEventListener('change',()=>{sessionStorage.setItem('harness-token',$('token').value.trim());load(false,true)});$('repository').addEventListener('change',()=>sessionStorage.setItem('harness-repo',$('repository').value.trim()));$('taskForm').addEventListener('submit',startTask);$('batchForm').addEventListener('submit',startBatch);$('yamlBatchForm').addEventListener('submit',startYamlBatch);$('addBatchTask').addEventListener('click',()=>addBatchRow());$('fillBatchExample').addEventListener('click',()=>{$('batchManifest').value=batchTemplate();$('batchManifest').focus()});$('clearBatch').addEventListener('click',()=>{$('batchManifest').value='';$('batchManifest').focus()});$('parallelTask').addEventListener('change',changeParallelMode);$('workspaceMode').addEventListener('change',syncWorkspaceHelp);$('goal').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')$('taskForm').requestSubmit()});$('refresh').addEventListener('click',()=>load(false,true));$('focusTask').addEventListener('click',()=>{$('newTaskPanel').scrollIntoView({behavior:'smooth'});$('goal').focus()});$('jumpAttention').addEventListener('click',()=>$('attentionPanel').scrollIntoView({behavior:'smooth'}));$('jumpHistory').addEventListener('click',()=>$('historyPanel').scrollIntoView({behavior:'smooth'}));$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});$('clearFilters').addEventListener('click',clearTaskFilters);[['repositoryFilter','repository'],['branchFilter','branch'],['workerFilter','worker']].forEach(([id,key])=>$(id).addEventListener('change',()=>{state[key]=$(id).value;renderTasks()}));syncWorkspaceHelp();addBatchRow();api('/config').then(config=>{if(!$('repository').value){$('repository').value=config.default_repository||'';sessionStorage.setItem('harness-repo',$('repository').value)}document.querySelectorAll('.batch-repository').forEach(input=>{if(!input.value)input.value=$('repository').value});return load()}).catch(e=>toast(e.message,true));setInterval(()=>load(true),5000)}
bootstrap();
</script>
</body>
</html>'''
